server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka
      instance:
      prefer-ip-address: true
  config:
    import: optional:configserver:http://localhost:8085   
      

  application:
      name: RATING-SERVICE
      
okta:
  oauth2:
    issuer: https://dev-60210024.okta.com/oauth2/default
    audience: api://default